FROM node:18-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Expose port for the dev server
EXPOSE 3000

# Start the app in development mode
CMD ["npm", "start"]

